const bank = [
  {
    id: 1,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "The Islets of Langerhans is found in which human organ?",
    correct_answers: ["Pancreas"],
    all_answers: ["Kidney", "Liver", "Brain", "Pancreas"],
  },
  {
    id: 2,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question: "What is the hottest planet in the Solar System?",
    correct_answers: ["Venus"],
    all_answers: ["Mars", "Mercury", "Jupiter", "Venus"],
  },
  {
    id: 3,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which chemical element has the lowest boiling point?",
    correct_answers: ["Helium"],
    all_answers: ["Hydrogen", "Neon", "Nitrogen", "Helium"],
  },
  {
    id: 4,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "Which horizon in a soil profile consists of bedrock?",
    correct_answers: ["R"],
    all_answers: ["O", "B", "D", "R"],
  },
  {
    id: 5,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: 'Where did the dog breed "Chihuahua" originate?',
    correct_answers: ["Mexico"],
    all_answers: ["France", "Spain", "Russia", "Mexico"],
  },
  {
    id: 6,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which part of the body does glaucoma affect?",
    correct_answers: ["Eyes"],
    all_answers: ["Throat", "Stomach", "Blood", "Eyes"],
  },
  {
    id: 7,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: 'Which one of these is scientific term for "Brain Freeze"?',
    correct_answers: ["Sphenopalatine Ganglioneuralgia"],
    all_answers: [
      "Hyacinthoides Italica",
      "Amaranthus Retroflexus",
      "Amblyomma Americanum",
      "Sphenopalatine Ganglioneuralgia",
    ],
  },
  {
    id: 8,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question:
      "The element involved in making human blood red is which of the following?",
    correct_answers: ["Iron"],
    all_answers: ["Copper", "Iridium", "Cobalt", "Iron"],
  },
  {
    id: 9,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "The core of the Sun can reach which temperature?",
    correct_answers: ["27 Million F (15 Million C)"],
    all_answers: [
      "938,000; F (521093.3 C)",
      "8 Billion F (4.4 Billion C)",
      "Absolute Zero (Both F and C)",
      "27 Million F (15 Million C)",
    ],
  },
  {
    id: 10,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which of these elements on the Periodic Table is a Noble Gas?",
    correct_answers: ["Neon"],
    all_answers: ["Potassium", "Iodine", "Colbalt", "Neon"],
  },
  {
    id: 11,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question: "How many chromosomes are in your body cells?",
    correct_answers: ["23"],
    all_answers: ["21", "22", "24", "23"],
  },
  {
    id: 12,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "What is the same in Celsius and Fahrenheit?",
    correct_answers: ["-40"],
    all_answers: ["32", "-39", "-42", "-40"],
  },
  {
    id: 13,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which chemical element was originally known as Alabamine?",
    correct_answers: ["Astatine"],
    all_answers: ["Selenium", "Antimony", "Molybdenum", "Astatine"],
  },
  {
    id: 14,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: 'What is the scientific term for "Taste"?',
    correct_answers: ["Gustatory Perception"],
    all_answers: [
      "Olfaction",
      "Somatosensation",
      "Auditory Perception",
      "Gustatory Perception",
    ],
  },
  {
    id: 15,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Where did the Great Storm of 1987 make landfall at, first?",
    correct_answers: ["Cornwall"],
    all_answers: ["Surrey", "Wales", "The Midlands", "Cornwall"],
  },
  {
    id: 16,
    category: "Science: Computers",
    type: "multiple",
    question:
      "Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?",
    correct_answers: ["Apple"],
    all_answers: ["Microsoft", "Atari", "Commodore", "Apple"],
  },
  {
    id: 17,
    category: "Science: Computers",
    type: "multiple",
    question: "What does CPU stand for?",
    correct_answers: ["Central Processing Unit"],
    all_answers: [
      "Central Process Unit",
      "Computer Personal Unit",
      "Central Processor Unit",
      "Central Processing Unit",
    ],
  },
  {
    id: 18,
    category: "Science: Computers",
    type: "multiple",
    question:
      "What was the name of the security vulnerability found in Bash in 2014?",
    correct_answers: ["Shellshock"],
    all_answers: ["Heartbleed", "Bashbug", "Stagefright", "Shellshock"],
  },
  {
    id: 19,
    category: "Science: Computers",
    type: "multiple",
    question:
      "When Gmail first launched, how much storage did it provide for your email?",
    correct_answers: ["1GB"],
    all_answers: ["512MB", "5GB", "Unlimited", "1GB"],
  },
  {
    id: 20,
    category: "Science: Computers",
    type: "multiple",
    question: "What five letter word is the motto of the IBM Computer company?",
    correct_answers: ["Think"],
    all_answers: ["Click", "Logic", "Pixel", "Think"],
  },
  {
    id: 21,
    category: "Science: Computers",
    type: "multiple",
    question: "What amount of bits commonly equals one byte?",
    correct_answers: ["8"],
    all_answers: ["1", "2", "64", "8"],
  },
  {
    id: 22,
    category: "Science: Computers",
    type: "multiple",
    question: "On which computer hardware device is the BIOS chip located?",
    correct_answers: ["Motherboard"],
    all_answers: [
      "Hard Disk Drive",
      "Central Processing Unit",
      "Graphics Processing Unit",
      "Motherboard",
    ],
  },
  {
    id: 23,
    category: "Science: Computers",
    type: "multiple",
    question:
      "All of the following programs are classified as raster graphics editors EXCEPT:",
    correct_answers: ["Inkscape"],
    all_answers: ["Paint.NET", "GIMP", "Adobe Photoshop", "Inkscape"],
  },
  {
    id: 24,
    category: "Science: Computers",
    type: "multiple",
    question:
      "What did the name of the Tor Anonymity Network orignially stand for?",
    correct_answers: ["The Onion Router"],
    all_answers: [
      "The Only Router",
      "The Orange Router",
      "The Ominous Router",
      "The Onion Router",
    ],
  },
  {
    id: 25,
    category: "Science: Computers",
    type: "multiple",
    question: "What was the first commerically available computer processor?",
    correct_answers: ["Intel 4004"],
    all_answers: ["Intel 486SX", "TMS 1000", "AMD AM386", "Intel 4004"],
  },
  {
    id: 26,
    category: "Science: Computers",
    type: "multiple",
    question: "What was the name given to Android 4.3?",
    correct_answers: ["Jelly Bean"],
    all_answers: ["Lollipop", "Nutella", "Froyo", "Jelly Bean"],
  },
  {
    id: 27,
    category: "Science: Computers",
    type: "multiple",
    question: "What is the domain name for the country Tuvalu?",
    correct_answers: [".tv"],
    all_answers: [".tu", ".tt", ".tl", ".tv"],
  },
  {
    id: 28,
    category: "Science: Computers",
    type: "multiple",
    question: "Generally, which component of a computer draws the most power?",
    correct_answers: ["Video Card"],
    all_answers: ["Hard Drive", "Processor", "Power Supply", "Video Card"],
  },
  {
    id: 29,
    category: "Science: Computers",
    type: "multiple",
    question: "How many cores does the Intel i7-6950X have?",
    correct_answers: ["10"],
    all_answers: ["12", "8", "4", "10"],
  },
  {
    id: 30,
    category: "Science: Computers",
    type: "multiple",
    question: "How fast is USB 3.1 Gen 2 theoretically?",
    correct_answers: ["10 Gb/s"],
    all_answers: ["5 Gb/s", "8 Gb/s", "1 Gb/s", "10 Gb/s"],
  },
  {
    id: 31,
    category: "Science: Computers",
    type: "multiple",
    question:
      "Which of the following is a personal computer made by the Japanese company Fujitsu?",
    correct_answers: ["FM-7"],
    all_answers: ["PC-9801", "Xmillennium ", "MSX", "FM-7"],
  },
  {
    id: 32,
    category: "Science: Computers",
    type: "multiple",
    question: ".rs is the top-level domain for what country?",
    correct_answers: ["Serbia"],
    all_answers: ["Romania", "Russia", "Rwanda", "Serbia"],
  },
  {
    id: 33,
    category: "Science: Computers",
    type: "multiple",
    question:
      "The numbering system with a radix of 16 is more commonly referred to as ",
    correct_answers: ["Hexidecimal"],
    all_answers: ["Binary", "Duodecimal", "Octal", "Hexidecimal"],
  },
  {
    id: 34,
    category: "Science: Computers",
    type: "multiple",
    question: "What is known as &quot;the brain&quot; of the Computer?",
    correct_answers: ["Central Processing Unit"],
    all_answers: [
      "Motherboard",
      "Graphics Processing Unit",
      "Keyboard",
      "Central Processing Unit",
    ],
  },
  {
    id: 35,
    category: "Science: Computers",
    type: "multiple",
    question: "What does the term GPU stand for?",
    correct_answers: ["Graphics Processing Unit"],
    all_answers: [
      "Gaming Processor Unit",
      "Graphite Producing Unit",
      "Graphical Proprietary Unit",
      "Graphics Processing Unit",
    ],
  },
  {
    id: 36,
    category: "Science: Computers",
    type: "multiple",
    question:
      "What is the name of the process that sends one qubit of information using two bits of classical information?",
    correct_answers: ["Quantum Teleportation"],
    all_answers: [
      "Super Dense Coding",
      "Quantum Entanglement",
      "Quantum Programming",
      "Quantum Teleportation",
    ],
  },
  {
    id: 37,
    category: "Science: Computers",
    type: "multiple",
    question: "What internet protocol was documented in RFC 1459?",
    correct_answers: ["IRC"],
    all_answers: ["HTTP", "HTTPS", "FTP", "IRC"],
  },
  {
    id: 38,
    category: "Science: Computers",
    type: "multiple",
    question:
      "Which of these is not a key value of Agile software development?",
    correct_answers: ["Comprehensive documentation"],
    all_answers: [
      "Individuals and interactions",
      "Customer collaboration",
      "Responding to change",
      "Comprehensive documentation",
    ],
  },
  {
    id: 39,
    category: "Science: Computers",
    type: "multiple",
    question: "What is the main CPU is the Sega Mega Drive / Sega Genesis?",
    correct_answers: ["Motorola 68000"],
    all_answers: ["Zilog Z80", "Yamaha YM2612", "Intel 8088", "Motorola 68000"],
  },
  {
    id: 40,
    category: "Science: Computers",
    type: "multiple",
    question:
      "Laserjet and inkjet printers are both examples of what type of printer?",
    correct_answers: ["Non-impact printer"],
    all_answers: [
      "Impact printer",
      "Daisywheel printer",
      "Dot matrix printer",
      "Non-impact printer",
    ],
  },
  {
    id: 41,
    category: "Science: Computers",
    type: "multiple",
    question:
      "Which programming language was developed by Sun Microsystems in 1995?",
    correct_answers: ["Java"],
    all_answers: ["Python", "Solaris OS", "C++", "Java"],
  },
  {
    id: 42,
    category: "Science: Computers",
    type: "multiple",
    question: "Who invented the &quot;Spanning Tree Protocol&quot;?",
    correct_answers: ["Radia Perlman"],
    all_answers: [
      "Paul Vixie",
      "Vint Cerf",
      "Michael Roberts",
      "Radia Perlman",
    ],
  },
  {
    id: 43,
    category: "Science: Computers",
    type: "multiple",
    question: "In computing, what does MIDI stand for?",
    correct_answers: ["Musical Instrument Digital Interface"],
    all_answers: [
      "Musical Interface of Digital Instruments",
      "Modular Interface of Digital Instruments",
      "Musical Instrument Data Interface",
      "Musical Instrument Digital Interface",
    ],
  },
  {
    id: 44,
    category: "Science: Computers",
    type: "multiple",
    question: "How many bytes are in a single Kibibyte?",
    correct_answers: ["1024"],
    all_answers: ["2400", "1000", "1240", "1024"],
  },
  {
    id: 45,
    category: "Science: Computers",
    type: "multiple",
    question: "What major programming language does Unreal Engine 4 use?",
    correct_answers: ["C++"],
    all_answers: ["Assembly", "C#", "ECMAScript", "C++"],
  },
];

export default bank;
