const bank = [
  {
    id: 1,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question:
      "The Islets of Langerhans is found in which human organ?",
    correct_answers: ["Pancreas"],
    all_answers: ["Kidney", "Liver", "Brain", "Pancreas"],
  },
  {
    id: 2,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question: "What is the hottest planet in the Solar System?",
    correct_answers: ["Venus"],
    all_answers: ["Mars", "Mercury", "Jupiter", "Venus"],
  },
  {
    id: 3,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which chemical element has the lowest boiling point?",
    correct_answers: ["Helium"],
    all_answers: ["Hydrogen", "Neon", "Nitrogen", "Helium"],
  },
  {
    id: 4,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "Which horizon in a soil profile consists of bedrock?",
    correct_answers: ["R"],
    all_answers: ["O", "B", "D", "R"],
  },
  {
    id: 5,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: 'Where did the dog breed "Chihuahua" originate?',
    correct_answers: ["Mexico"],
    all_answers: ["France", "Spain", "Russia", "Mexico"],
  },
  {
    id: 6,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which part of the body does glaucoma affect?",
    correct_answers: ["Eyes"],
    all_answers: ["Throat", "Stomach", "Blood", "Eyes"],
  },
  {
    id: 7,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: 'Which one of these is scientific term for "Brain Freeze"?',
    correct_answers: ["Sphenopalatine Ganglioneuralgia"],
    all_answers: [
      "Hyacinthoides Italica",
      "Amaranthus Retroflexus",
      "Amblyomma Americanum",
      "Sphenopalatine Ganglioneuralgia",
    ],
  },
  {
    id: 8,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question:
      "The element involved in making human blood red is which of the following?",
    correct_answers: ["Iron"],
    all_answers: ["Copper", "Iridium", "Cobalt", "Iron"],
  },
  {
    id: 9,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "The core of the Sun can reach which temperature?",
    correct_answers: ["27 Million F (15 Million C)"],
    all_answers: [
      "938,000; F (521093.3 C)",
      "8 Billion F (4.4 Billion C)",
      "Absolute Zero (Both F and C)",
      "27 Million F (15 Million C)",
    ],
  },
  {
    id: 10,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which of these elements on the Periodic Table is a Noble Gas?",
    correct_answers: ["Neon"],
    all_answers: ["Potassium", "Iodine", "Colbalt", "Neon"],
  },
  {
    id: 11,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question: "How many chromosomes are in your body cells?",
    correct_answers: ["23"],
    all_answers: ["21", "22", "24", "23"],
  },
  {
    id: 12,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "What is the same in Celsius and Fahrenheit?",
    correct_answers: ["-40"],
    all_answers: ["32", "-39", "-42", "-40"],
  },
  {
    id: 13,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which chemical element was originally known as Alabamine?",
    correct_answers: ["Astatine"],
    all_answers: ["Selenium", "Antimony", "Molybdenum", "Astatine"],
  },
  {
    id: 14,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: 'What is the scientific term for "Taste"?',
    correct_answers: ["Gustatory Perception"],
    all_answers: [
      "Olfaction",
      "Somatosensation",
      "Auditory Perception",
      "Gustatory Perception",
    ],
  },
  {
    id: 15,
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Where did the Great Storm of 1987 make landfall at, first?",
    correct_answers: ["Cornwall"],
    all_answers: ["Surrey", "Wales", "The Midlands", "Cornwall"],
  },
];

export default bank;
