const bank = [
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question:
      "The &#039;Islets of Langerhans&#039; is found in which human organ?",
    correct_answer: "Pancreas",
    incorrect_answers: ["Kidney", "Liver", "Brain"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question: "What is the hottest planet in the Solar System?",
    correct_answer: "Venus",
    incorrect_answers: ["Mars", "Mercury", "Jupiter"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which chemical element has the lowest boiling point?",
    correct_answer: "Helium",
    incorrect_answers: ["Hydrogen", "Neon", "Nitrogen"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "Which horizon in a soil profile consists of bedrock?",
    correct_answer: "R",
    incorrect_answers: ["O", "B", "D"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Where did the dog breed &quot;Chihuahua&quot; originate?",
    correct_answer: "Mexico",
    incorrect_answers: ["France", "Spain", "Russia"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which part of the body does glaucoma affect?",
    correct_answer: "Eyes",
    incorrect_answers: ["Throat", "Stomach", "Blood"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which one of these is scientific term for &quot;Brain Freeze&quot;?",
    correct_answer: "Sphenopalatine Ganglioneuralgia",
    incorrect_answers: [
      "Hyacinthoides Italica",
      "Amaranthus Retroflexus",
      "Amblyomma Americanum",
    ],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question:
      "The element involved in making human blood red is which of the following?",
    correct_answer: "Iron",
    incorrect_answers: ["Copper", "Iridium", "Cobalt"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "The core of the Sun can reach which temperature?",
    correct_answer: "27&deg; Million F (15&deg; Million C)",
    incorrect_answers: [
      "938,000&deg; F (521093.3&deg; C)",
      "8&deg; Billion F (&deg;4.4 Billion C)",
      "Absolute Zero (Both F and C)",
    ],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which of these elements on the Periodic Table is a Noble Gas?",
    correct_answer: "Neon",
    incorrect_answers: ["Potassium", "Iodine", "Colbalt"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "easy",
    question: "How many chromosomes are in your body cells?",
    correct_answer: "23",
    incorrect_answers: ["21", "22", "24"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "What is the same in Celsius and Fahrenheit?",
    correct_answer: "-40",
    incorrect_answers: ["32", "-39", "-42"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which chemical element was originally known as Alabamine?",
    correct_answer: "Astatine",
    incorrect_answers: ["Selenium", "Antimony", "Molybdenum"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "What is the scientific term for &#039;taste&#039;?",
    correct_answer: "Gustatory Perception",
    incorrect_answers: ["Olfaction", "Somatosensation", "Auditory Perception"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Where did the Great Storm of 1987 make landfall at, first?",
    correct_answer: "Cornwall",
    incorrect_answers: ["Surrey", "Wales", "The Midlands"],
  },
];

export default bank
